### ISSUE TITLE
Some echo or error when I open the terminal

### ISSUE THREAD

**Issue by byman64** [babakks/vscode-copy-from-terminal#17]
Here what I see when I open a new terminal.

`root@vps:~/mybatch/snippets# export COPY_TO_VSCODE_TEMP_DIR="/root/.vscode-server/extensions/babakks.vscode-copy-from-terminal-0.0.7/temp/" && export EXTENSION_INSTANCE_ID="aa47" && _get_temp_file() { dt="$(date --iso-8601=ns)" && tempfname="$dt-$EXTENSION_INSTANCE_ID.tmp" && echo "$COPY_TO_VSCODE_TEMP_DIR/$tempfname"; } && cp2code() { cat > "$(_get_temp_file)"; } && tee2code() { tee "$(_get_temp_file)"; }
root@vps:~/mybatch/snippets# `

cp2code works, but would be nice clean up it

Visual Studio Code Version 1.70.2

Let me know if you need more details

**Comment by babakks** [comment]
Thanks for your feedback @byman64. The problem with that is VS Code does not permit extensions to execute hidden commands in the shell. Of course, we can clean this up to a shorter command, like a shell script invocation call.

I'll try to make it cleaner. You are also always welcome to submit a PR.

**Comment by byman64** [comment]
Just another info, also bash_history is dirty. If I press arrow-up I see the followinf long command.    Pls let me know when you will fix. I will test it regards  Antonino MiglioreParma - Italy Da: Babak K. ShandizInviato: sabato 27 agosto 2022 13:04A: babakks/vscode-copy-from-terminalCc: byman64; MentionOggetto: Re: [babakks/vscode-copy-from-terminal] Some echo or error when I open the terminal (Issue #17) Thanks for your feedback @byman64. The problem with that is VS Code does not permit extensions to execute hidden commands in the shell. Of course, we can clean this up to a shorter command, like a shell script invocation call.I'll try to make it cleaner. You are also always welcome to submit a PR.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by byman64** [comment]
I like your extension Pipe/Copy, really useful. I need help, maybe you can help me to clean history.
I create a simple bash script to clean the history:
`
grep -c -vw EXTENSION_INSTANCE_ID /root/screenhistory/.bash_history. > /root/screenhistory/.bash_history.

`
it works fine, it will remove your lines like the following:
`
root@vps:~# export COPY_TO_VSCODE_TEMP_DIR="/root/.vscode-server/extensions/babakks.vscode-copy-from-terminal-0.0.7/temp/" && export EXTENSION_INSTANCE_ID="f7bd" && _get_temp_file() { dt="$(date --iso-8601=ns)" && tempfname="$dt-$EXTENSION_INSTANCE_ID.tmp" && echo "$COPY_TO_VSCODE_TEMP_DIR/$tempfname"; } && cp2code() { cat > "$(_get_temp_file)"; } && tee2code() { tee "$(_get_temp_file)"; }

`

I just need where put it in the tree of bash script when I open a terminal. I tried to put the clean bash history in the following without success:
- .bashrc
- .screenrc
I don't know but I feel there is a custom rc for code

Pls let me know if you can help me...I am still searching where put my grep to clean up the history

**Comment by babakks** [comment]
For the bash history update, I think you should assign the `COMMAND_PROMPT` environment variable in `.bashrc` with your grep/redirect command. See [here][cp] for more details.

[cp]: https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x264.html

However, I'd soon update the extension to prepend a single whitespace to the initializer command and thus preventing it from showing up in the history. I'll update you when I've uploaded the new version.

**Comment by babakks** [comment]
@byman64 I've just published the new version. Could you please upgrade your installation?

The shell history problem should is now resolved. The initializer command is also improved into a one-liner.

**Comment by byman64** [comment]
I think it's Ok, update installed and finally is acceptable. I see only the following string and history finally is clean 
`root@vps:~#  _bp="/root/.vscode-server/extensions/babakks.vscode-copy-from-terminal-0.0.8"; . "$_bp/script/init.sh" "1165" "$_bp/temp" "cp2code" "tee2code"

root@vps:~# 
`

[OT] 
I also see your extension as LOCAL but cannot update it. I get an error. What is your suggest?
Remove from local, manually update or whatelse?

**Comment by babakks** [comment]
Could you please give more info on the error? VS Code outputs pane is a good help, but I'm not sure which stream would reflect the error (maybe "main/window" or "shared")

**Comment by byman64** [comment]
1 - I open code and I have seen an update available for local installation (I didnt install locally but maybe it's a normal process)
2 - tried to update the local version and I got an error:
      Error while updating 'Copy/Pipe From Terminal' extension. 
     Please check the [log](command:workbench.action.showWindowLog) for more details. 
     _(see the below error report.)_
3 - Update was succesfully installed on the remote server 

Let me know if I can give you more details and how. If you want I could try to install it manually as the message box suggests.

wait for your instructions
ciao


**ERROR LOG**
`
[2022-08-29 20:43:34.535] [renderer1] [warning] [vscode.references-view]: Cannot register 'references.preferredLocation'. This property is already registered.
[2022-08-29 20:43:34.539] [renderer1] [warning] [zobo.php-intellisense]: Cannot register 'php.memoryLimit'. This property is already registered.
[2022-08-29 20:43:34.541] [renderer1] [warning] [zobo.php-intellisense]: Cannot register 'php.executablePath'. This property is already registered.
[2022-08-29 20:43:34.844] [renderer1] [error] [sidthesloth.html5-boilerplate]: Unknown language in `contributes.html5-boilerplate.language`. Provided value: njk
[2022-08-29 20:43:34.844] [renderer1] [error] [sidthesloth.html5-boilerplate]: Unknown language in `contributes.html5-boilerplate.language`. Provided value: django-html
[2022-08-29 20:43:34.845] [renderer1] [error] [vscode.references-view]: Cannot register multiple views with same id `references-view.tree`
[2022-08-29 20:43:34.845] [renderer1] [error] [DaGhostman.vs-treeview]: Cannot register multiple views with same id `sidebar-outline`
[2022-08-29 20:43:38.954] [renderer1] [info] UNRESPONSIVE extension host: starting to profile NOW
[2022-08-29 20:43:40.943] [renderer1] [error] [Extension Host] (node:14936) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-08-29 20:43:41.984] [renderer1] [info] UNRESPONSIVE extension host: received responsive event and cancelling profiling session
[2022-08-29 20:43:42.358] [renderer1] [warning] UNRESPONSIVE extension host: 'lkytal.translatorplus' took 57% of 3141.447ms, saved PROFILE here: 'file:///c%3A/Users/byman/AppData/Local/Temp/exthost-4aad74.cpuprofile' [{"id":"cweijan.vscode-myssql-client2","total":230,"percentage":0},{"id":"gc","total":9450,"percentage":0},{"id":"lkytal.translatorplus","total":1802514,"percentage":57},{"id":"program","total":562,"percentage":0},{"id":"self","total":1245786,"percentage":40},{"id":"wayou.vscode-todo-highlight","total":15198,"percentage":0},{"id":"Zignd.html-css-class-completion","total":67542,"percentage":2}]
[2022-08-29 20:43:43.729] [renderer1] [error] ENOENT: no such file or directory, open 'c:\StoragePool\ScanDisk-1TB\byman\Appx\Developing\vscode\data\extensions\.57e530a5-6988-4907-9ad5-32614ef861df\temp\2022-08-29T09:46:37,194773238+04:30-e634.tmp': Extract: ENOENT: no such file or directory, open 'c:\StoragePool\ScanDisk-1TB\byman\Appx\Developing\vscode\data\extensions\.57e530a5-6988-4907-9ad5-32614ef861df\temp\2022-08-29T09:46:37,194773238+04:30-e634.tmp'
    at J.extractAtLocation (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:162642)
    at async J.extractUserExtension (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:160029)
    at async Q.extract (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:166973)
    at async Q.doRun (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:168240)
[2022-08-29 20:43:50.403] [renderer1] [info] [attempt 1] Invoking resolveAuthority(ssh-remote)
[2022-08-29 20:43:56.620] [renderer1] [info] [attempt 1] resolveAuthority(ssh-remote) returned '127.0.0.1:50782' after 6162 ms
[2022-08-29 20:43:56.621] [renderer1] [error] [Extension Host] (node:16920) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-08-29 20:43:58.361] [renderer1] [error] [sidthesloth.html5-boilerplate]: Unknown language in `contributes.html5-boilerplate.language`. Provided value: njk
[2022-08-29 20:43:58.361] [renderer1] [error] [sidthesloth.html5-boilerplate]: Unknown language in `contributes.html5-boilerplate.language`. Provided value: django-html
[2022-08-29 20:44:01.988] [renderer1] [error] ENOENT: no such file or directory, open 'c:\StoragePool\ScanDisk-1TB\byman\Appx\Developing\vscode\data\extensions\.57e530a5-6988-4907-9ad5-32614ef861df\temp\2022-08-29T09:46:37,194773238+04:30-e634.tmp': Extract: ENOENT: no such file or directory, open 'c:\StoragePool\ScanDisk-1TB\byman\Appx\Developing\vscode\data\extensions\.57e530a5-6988-4907-9ad5-32614ef861df\temp\2022-08-29T09:46:37,194773238+04:30-e634.tmp'
    at J.extractAtLocation (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:162642)
    at async J.extractUserExtension (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:160029)
    at async Q.extract (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:166973)
    at async Q.doRun (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:168240)
[2022-08-29 20:48:43.309] [renderer1] [error] ["Extract: ENOENT: no such file or directory, open 'c:\\StoragePool\\ScanDisk-1TB\\byman\\Appx\\Developing\\vscode\\data\\extensions\\.57e530a5-6988-4907-9ad5-32614ef861df\\temp\\2022-08-29T09:46:37,194773238+04:30-e634.tmp'","    at J.extractAtLocation (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:162642)","    at async J.extractUserExtension (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:160029)","    at async Q.extract (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:166973)","    at async Q.doRun (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:168240)"]
[2022-08-29 20:48:43.348] [renderer1] [error] ENOENT: no such file or directory, open 'c:\StoragePool\ScanDisk-1TB\byman\Appx\Developing\vscode\data\extensions\.57e530a5-6988-4907-9ad5-32614ef861df\temp\2022-08-29T09:46:37,194773238+04:30-e634.tmp': Extract: ENOENT: no such file or directory, open 'c:\StoragePool\ScanDisk-1TB\byman\Appx\Developing\vscode\data\extensions\.57e530a5-6988-4907-9ad5-32614ef861df\temp\2022-08-29T09:46:37,194773238+04:30-e634.tmp'
    at J.extractAtLocation (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:162642)
    at async J.extractUserExtension (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:160029)
    at async Q.extract (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:166973)
    at async Q.doRun (vscode-file://vscode-app/c:/StoragePool/ScanDisk-1TB/byman/Appx/Developing/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:168240)

`

**Comment by byman64** [comment]
FIXED: 
Extension removed  from Local and intalled again. 
Now I have the v0.0.8 in both system: PC and Remote

**Comment by babakks** [comment]
I don't think so. This extension runs on the remote-host (if any) and thus you wouldn't need it on the local host. Also, the extension does not work on Windows as host (unless you use git-bash in the integrated terminal).

**Comment by byman64** [comment]
Perfect I thought that, infact I removed. 
grazie
ciao
